[package]
name = "text2hex"
version = "0.1.1"
edition = "2024"
description = "Converts command-line input (UTF-8) into hexadecimal"
repository = "https://github.com/mattaroni/text2hex"
license = "MIT"
publish = false # for now at least

[dependencies]
